// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: xlsx_service.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for requesting XLSX data.
// Contains the file path of the XLSX file to be streamed.
type GetXlsxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"` // The path to the XLSX file on the server.
}

func (x *GetXlsxRequest) Reset() {
	*x = GetXlsxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xlsx_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXlsxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXlsxRequest) ProtoMessage() {}

func (x *GetXlsxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xlsx_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXlsxRequest.ProtoReflect.Descriptor instead.
func (*GetXlsxRequest) Descriptor() ([]byte, []int) {
	return file_xlsx_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetXlsxRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// Data chunk of the XLSX file.
// Each message contains a part of the file's data.
type XlsxDataChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"` // A chunk of the XLSX file data.
}

func (x *XlsxDataChunk) Reset() {
	*x = XlsxDataChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xlsx_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XlsxDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XlsxDataChunk) ProtoMessage() {}

func (x *XlsxDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_xlsx_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XlsxDataChunk.ProtoReflect.Descriptor instead.
func (*XlsxDataChunk) Descriptor() ([]byte, []int) {
	return file_xlsx_service_proto_rawDescGZIP(), []int{1}
}

func (x *XlsxDataChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_xlsx_service_proto protoreflect.FileDescriptor

var file_xlsx_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x78, 0x6c, 0x73, 0x78, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x78, 0x6c, 0x73, 0x78, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x58, 0x6c, 0x73, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22,
	0x25, 0x0a, 0x0d, 0x58, 0x6c, 0x73, 0x78, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0x57, 0x0a, 0x0b, 0x58, 0x6c, 0x73, 0x78, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x58, 0x6c, 0x73, 0x78,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x78, 0x6c, 0x73, 0x78, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x6c, 0x73, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x78, 0x6c, 0x73, 0x78, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x58, 0x6c, 0x73, 0x78, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x7a, 0x67, 0x6f, 0x72, 0x64, 0x61, 0x6e, 0x2d, 0x76, 0x76, 0x2f, 0x64, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x5f, 0x69, 0x6d, 0x65, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_xlsx_service_proto_rawDescOnce sync.Once
	file_xlsx_service_proto_rawDescData = file_xlsx_service_proto_rawDesc
)

func file_xlsx_service_proto_rawDescGZIP() []byte {
	file_xlsx_service_proto_rawDescOnce.Do(func() {
		file_xlsx_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_xlsx_service_proto_rawDescData)
	})
	return file_xlsx_service_proto_rawDescData
}

var file_xlsx_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xlsx_service_proto_goTypes = []interface{}{
	(*GetXlsxRequest)(nil), // 0: xlsxservice.GetXlsxRequest
	(*XlsxDataChunk)(nil),  // 1: xlsxservice.XlsxDataChunk
}
var file_xlsx_service_proto_depIdxs = []int32{
	0, // 0: xlsxservice.XlsxService.GetXlsxData:input_type -> xlsxservice.GetXlsxRequest
	1, // 1: xlsxservice.XlsxService.GetXlsxData:output_type -> xlsxservice.XlsxDataChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xlsx_service_proto_init() }
func file_xlsx_service_proto_init() {
	if File_xlsx_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xlsx_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXlsxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xlsx_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XlsxDataChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xlsx_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xlsx_service_proto_goTypes,
		DependencyIndexes: file_xlsx_service_proto_depIdxs,
		MessageInfos:      file_xlsx_service_proto_msgTypes,
	}.Build()
	File_xlsx_service_proto = out.File
	file_xlsx_service_proto_rawDesc = nil
	file_xlsx_service_proto_goTypes = nil
	file_xlsx_service_proto_depIdxs = nil
}
